#!/bin/bash

touch Gemfile.lock
touch Gemfile
touch LICENSE
touch vue.config.js
touch nuxt.config.js
touch next.config.js
touch next.config.mjs
touch mkdocs.yml
touch mkdocs.yaml
touch _config.toml
touch _config.yaml
touch _config.yml
touch hugo.yaml
touch hugo.toml
touch hugo.json
touch gatsby-config.js
touch gatsby-config.ts
touch bridgetown.config.yml
touch bridgetown.config.yaml
touch bridgetown.config.toml
touch astro.config.js
touch astro.config.mjs
touch astro.config.cjs
touch astro.config.ts
touch svelte.config.js
touch .eleventy.js
touch eleventy.config.js
touch eleventy.config.cjs
touch .eleventyignore
touch cloudcannon.config.json
touch cloudcannon.config.yml
touch cloudcannon.config.yaml
touch cloudcannon.config.js
touch cloudcannon.config.cjs
touch initial-build-settings.json
touch routing.json
touch ext.ts
touch ext.js
touch ext.cjs
touch ext.mjs
touch ext.mdx
touch ext.tsx
touch ext.jsx
touch ext.svx
touch ext.astre
touch ext.svelte
touch ext.vue
touch ext.ai
touch ext.css
touch ext.sass
touch ext.scss
touch ext.less
touch ext.json
touch ext.toml
touch ext.yml
touch ext.yaml
touch ext.properties
touch ext.csv
touch ext.tsv
touch ext.njk
touch ext.liquid
touch type-html.htm
touch type-html.html
touch type-markdown.md
touch type-markdown.mkd
touch type-markdown.markdown
touch type-markdown.mdown
touch type-markdown.mkdn
touch type-markdown.mdwn
touch type-markdown.mdtxt
touch type-markdown.mdtext
touch type-template.ejs
touch type-template.pug
touch type-template.haml
touch type-template.mustache
touch type-template.hbs
touch type-template.njk
touch type-template.liquid
touch type-template.svelte
touch type-template.svx
touch type-template.astro
touch type-template.jsx
touch type-template.tsx
touch type-template.mdx
touch type-template.vue
touch type-data.json
touch type-data.yml
touch type-data.toml
touch type-data.csv
touch type-data.tsv
touch type-data.yaml
touch type-data.properties
touch type-text.text
touch type-text.txt
touch type-text.rss
touch type-text.atom
touch type-text.xml
touch type-text.nbn
touch type-script.ts
touch type-script.js
touch type-script.mjs
touch type-script.cjs
touch type-script.coffee
touch type-stylesheet.css
touch type-stylesheet.less
touch type-stylesheet.sass
touch type-stylesheet.scss
touch type-compressed.zip
touch type-compressed.7z
touch type-compressed.tar
touch type-compressed.rar
touch type-compressed.gz
touch type-photoshop.psd
touch type-photoshop.pxm
touch type-video.mp4
touch type-video.mov
touch type-video.avi
touch type-video.wmv
touch type-video.webm
touch type-video.ogv
touch type-audio.mp3
touch type-audio.m4a
touch type-audio.ogg
touch type-audio.oga
touch type-audio.webma
touch type-audio.wav
touch type-image.ico
touch type-image.gif
touch type-image.jpeg
touch type-image.jpg
touch type-image.jpe
touch type-image.png
touch type-image.apng
touch type-image.webp
touch type-image.bmp
touch type-vector.svg
touch type-vector.svgz
touch type-font.woff
touch type-font.woff2
touch type-font.eot
touch type-font.ttf
touch type-font.tte
touch type-font.otf
touch type-pdf.pdf
touch type-word.doc
touch type-word.dot
touch type-word.docx
touch type-word.dotx
touch type-word.docm
touch type-word.dotm
touch type-excel.xsl
touch type-excel.xls
touch type-excel.xlt
touch type-excel.xla
touch type-excel.xlsx
touch type-excel.xltx
touch type-excel.xlsm
touch type-excel.xltm
touch type-excel.xlam
touch type-excel.xlsb
touch type-powerpoint.ppt
touch type-powerpoint.pot
touch type-powerpoint.pps
touch type-powerpoint.ppa
touch type-powerpoint.pptx
touch type-powerpoint.potx
touch type-powerpoint.ppsx
touch type-powerpoint.ppam
touch type-powerpoint.pptm
touch type-powerpoint.potm
touch type-powerpoint.ppsm
touch type-wasm.wasm
touch type-ruby.rb
touch type-misc.ics
touch type-misc.map
touch type-misc.srt
touch type-misc.vtt
touch type-misc.htc
touch type-misc.textile
touch type-misc.vcf
touch type-misc.appcache
touch type-cursor.cur
touch type-flash.swf
touch type-unity.unity3d
