collections_config:
  inputs:
    name: The Kitchen Sink
    description: All inputs configured in various states.
    documentation:
      url: 'https://cloudcannon.com/documentation/articles/how-to-choose-what-input-is-used-in-the-data-editor/'
      text: Inputs documentation
    path: inputs
    icon: list_alt
